### ISSUE TITLE
Meta concept #83842 -- Borderline

### ISSUE THREAD

**Issue by mirandajarnot** [monarch-initiative/HPO-UMLS-Integration#1]
Hi -- 
Below is a Metathesaurus concept report for Borderline.
Question:  is the HPO definition here narrower than the NCI definition?  Is the HPO atom OK to be included in this concept with the NCI and LNC atoms, or should HPO's Borderline be a separate concept?

CN# 83842  Borderline
CUI C0205189    Concept Status needs Review
STY Qualitative Concept   R
SCT {adjective/adjective phrase}
DEF [Release] HPO2015_04_20
- HPO2015_04_20/PT|Having a minor degree of severity that is
  considered to be on the boundary between the normal and the
  abnormal ranges. For quantitative traits, a deviation of that is
  less than two standard deviations from the appropriate
  population mean. [HPO:probinson]
  DEF [Release] NCI2015_02D
- NCI2015_02D/PT|Straddling the dividing line between two
  categories.
  DEF [Release] NCI2015_CDISC_1502D
- NCI2015_02D/PT|Straddling the dividing line between two
  categories.

ATOMS
  M         N []  Borderline [HPO2015_04_20/PT/HP:0012827]
              R        Borderline [NCI2015_02D/PT/C14157] C14157
               R        Borderline [NCI2015_02D/SY/TCGA] C14157
               R        Borderline [LNC250/LA/LA4259-3]
               R      BORDERLINE [NCI2015_CDISC_1502D/PT/C14157] C14157

CONTEXTS
   HPO2015_04_20/HPO2015_04_20/PT1/HP:0012827
   HPO
     All
       Clinical modifier
         Severity
          <Borderline>
           Mild
           Moderate
           Profound
           Severe
   NCI2015_02D/NCI2015_02D/PT1/C14157
   National Cancer Institute Thesaurus
     Property or Attribute
       Qualifier
         Disease Qualifier
           Disease Morphology Qualifier
            <Borderline>

Thanks,
Miranda Jarnot

**Comment by pnrobinson** [comment]
Looking here, 
http://nciterms.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&version=15.05d&code=C14157&ns=NCI_Thesaurus&key=n162833941&b=1&n=null

The NCI definition for borderline is "Straddling the dividing line between two categories.", therefore, this seems to be refering to something else altogether. For instance, you could straddle the border between severe and profound according to the NCI definition. 

I do not know what you mean by LNC atom, can you specify this please?

-thanks Peter

**Comment by mirandajarnot** [comment]
The LNC atom is the term from the LOINC vocabulary.  The atom name comes first in each row (Borderline), followed by the source vocabulary (LNC), term type (LA), and code (LA4259-3).
This concept also has NCI atoms and an HPO atom.
CN# 83842 Borderline
CUI C0205189 Concept Status needs Review
STY Qualitative Concept R
SCT {adjective/adjective phrase}
DEF [Release] HPO2015_04_20
-   HPO2015_04_20/PT|Having a minor degree of severity that is considered to be on the boundary between the normal and the abnormal ranges. For quantitative traits, a deviation of that is less than two standard deviations from the appropriate population mean. [HPO:probinson] DEF [Release] NCI2015_02D
-   NCI2015_02D/PT|Straddling the dividing line between two categories. DEF [Release] NCI2015_CDISC_1502D
-   NCI2015_02D/PT|Straddling the dividing line between two categories.
  ATOMS
  M N [] Borderline [HPO2015_04_20/PT/HP:0012827]
  R Borderline [NCI2015_02D/PT/C14157] C14157
  R Borderline [NCI2015_02D/SY/TCGA] C14157
  R Borderline [LNC250/LA/LA4259-3]
  R BORDERLINE [NCI2015_CDISC_1502D/PT/C14157] C14157

**Comment by mirandajarnot** [comment]
The LNC atom is the term from the LOINC vocabulary.  The atom name comes first in each row (Borderline), followed by the source vocabulary (LNC), term type (LA), and code (LA4259-3).
This concept also has NCI atoms and an HPO atom.
CN# 83842 Borderline
CUI C0205189 Concept Status needs Review
STY Qualitative Concept R
SCT {adjective/adjective phrase}
DEF [Release] HPO2015_04_20
• HPO2015_04_20/PT|Having a minor degree of severity that is considered to be on the boundary between the normal and the abnormal ranges. For quantitative traits, a deviation of that is less than two standard deviations from the appropriate population mean. [HPO:probinson] DEF [Release] NCI2015_02D
• NCI2015_02D/PT|Straddling the dividing line between two categories. DEF [Release] NCI2015_CDISC_1502D
• NCI2015_02D/PT|Straddling the dividing line between two categories.
ATOMS
M N [] Borderline [HPO2015_04_20/PT/HP:0012827]
R Borderline [NCI2015_02D/PT/C14157] C14157
R Borderline [NCI2015_02D/SY/TCGA] C14157
R Borderline [LNC250/LA/LA4259-3]
R BORDERLINE [NCI2015_CDISC_1502D/PT/C14157] C14157
