### ISSUE TITLE
Vertical gaze palsy

### ISSUE THREAD

**Issue by mirandajarnot** [monarch-initiative/HPO-UMLS-Integration#10]
HPO has Vertical Gaze Palsy and Vertical Supranuclear Gaze Palsy in the same concept (HP:0000511).  Are these truly synonymous, or is Vertical Gaze Palsy a broader term? See article below for alternative etiology of vertical gaze palsy:

http://stroke.ahajournals.org/content/26/8/1467.full

**Comment by pnrobinson** [comment]
I would like to take a closer look at this. In general, the HPO does not try to record etiologies. Some phenotypes tend to be described using etiological concepts ("supranuclear") but are so phenotypically distinct that there does not seem to be a better name for them. Nonetheless, let us think a little bit about the structure of the HPO in this area and see if this is a good synonym or not (note that probably some people use vertical gaze palsy simply as a synonym for VSGP)

**Comment by pnrobinson** [comment]
These are synonyms.
Gaze palsy (also gaze paresis) is a term used to indicate a symmetric limitation of the movements of both eyes in the same direction (ie, a conjugate ophthalmoplegia). 
The word supranuclear refers to  a cerebral lesion, above the nucleus that supplies the cranial nerve responsible for the corresponding movement. (The supranuclear structures assure that the nuclei, and cranial nerves, on both sides, are activated in a coordinated fashion). 
This is the reason why supranuclear gaze palsy is a good phenotype term -- it is a distinctive phenotype.
I will add the "supranuclear" subhierarchy to the "Abnormal conjugate eye movement" section as a child.
I will also add a new term "Internuclear ophthalmoplegia".

**Comment by pnrobinson** [comment]
PS., the gaze palsy described in the article you refered to http://stroke.ahajournals.org/content/26/8/1467.full is also supranuclear (cerebral), even though the authors do not refer to it in this way.
