### ISSUE TITLE
Obliteration of frontal sinuses HP:0005452

### ISSUE THREAD

**Issue by mirandajarnot** [monarch-initiative/HPO-UMLS-Integration#11]
For this concept, do you mean the medical procedure to obliterate the frontal sinuses, or do you mean it as an anatomical abnormality where the sinuses are absent?

**Comment by markengelstad** [comment]
medical procedure

filling the frontal sinus with fat, bone, muscle, or other tissue with the
intent of obliterating the sinus cavity and sealing off the frontal sinus
ostium from the rest of the paranasal sinuses

**Comment by mirandajarnot** [comment]
Thank you!

**Comment by pnrobinson** [comment]
Actually, I think that this term was derived from this OMIM entry
http://omim.org/clinicalSynopsis/224300
and it was intended to mean absence of the frontal sinus. It is obvious from Mark's email that the term name is not good and needs to be changed accordingly. The HPO does not include any terms that refer to medical procedures or (directly) to their consequences.
So, I would suggest we rename the term and provide a textual definition. I will add this to the HPO tracker.
thanks!
-Peter

**Comment by markengelstad** [comment]
yes... obliteration implies that it was once there (present) and somehow removed (obliterated).  

absence is better quality

mark
