### ISSUE TITLE
Intracranial Hypotension

### ISSUE THREAD

**Issue by mirandajarnot** [monarch-initiative/HPO-UMLS-Integration#12]
For the HPO term Intracranial Hypotension (HP:0012641), do you mean the finding of decreased intracranial pressure, or do you mean it as the disease state/disorder that can result from it?

**Comment by pnrobinson** [comment]
We mean the finding (See the definition:)
A reduction of the pressure inside the cranium (skull) and thereby in the brain tissue and cerebrospinal fluid.

**Comment by mirandajarnot** [comment]
Thank you; that is what I thought from your definition, but wanted to make sure.

**Comment by iamkoehler** [comment]
Closing as seems to be resolved
