### ISSUE TITLE
Abnormality of the heart valves  (HP:0001654)

### ISSUE THREAD

**Issue by mirandajarnot** [monarch-initiative/HPO-UMLS-Integration#13]
For this concept, do you mean the anatomical or functional abnormality of the valve itself, or the disease/syndrome resulting from the abnormality?  The meaning is unclear from the terms and the definition.
There are two terms in the concept that say "abnormality", and one that says "disease".  The definition states only "An abnormality of a Cardiac valve."
Thanks for any clarification on this concept.

**Comment by iamkoehler** [comment]
It is referring to any abnormality (functional or morphological) of the valves. @pnrobinson please advise if  I can remove the exact synonym "Valvular heart disease"!

**Comment by pnrobinson** [comment]
The term is meant to be a phenotypic abnormality and not a disease entity. As with many other examples, usage in the literature varies. The term did have some EXACT_SYNONYMS such as vavular heart disease that we have now changed to RELATED SYNONYMS. Is that OK?

**Comment by mirandajarnot** [comment]
That should be fine.  Thank you!
