### ISSUE TITLE
Inappropriate Sinus Tachycardia  [HP:0011703]

### ISSUE THREAD

**Issue by mirandajarnot** [monarch-initiative/HPO-UMLS-Integration#14]
Inappropriate Sinus Tachycardia is in HPO as a synonym of Sinus Tachycardia.  Should it be a separate (narrower) concept, since there are other forms of sinus tachycardia?  We have two very distinct concepts for these in the Metathesaurus.

Thanks.

**Comment by iamkoehler** [comment]
@pnrobinson  please reopen if not happy
