### ISSUE TITLE
Meta Concept #44586194 -- Generalized Seizures

### ISSUE THREAD

**Issue by mirandajarnot** [monarch-initiative/HPO-UMLS-Integration#2]
HPO has "Afebrile Seizure" and "Recurrent Seizure" as synonyms.  They are not the same thing and should not be SY. 

CN# 44586194 Generalized seizures
CUI C1833488 Concept Status needs Review
CUI C1843143
STY Finding N
DEF [Release] HPO2015_04_20
- HPO2015_04_20/PT|Seizures of with initial involvement of both
  cerebral hemispheres. [HPO:probinson]
  ATOMS
  DM A N [] Generalized seizures [HPO2015_04_20/PT/HP:0002197]
  Y R Generalized seizures <2> [MTH/TM/U466293]
  M N [] Generalized seizures, recurrent [HPO2015_04_20/SY/HP:0002197]
  R Generalized seizures, recurrent [OMIM2015_03_18/PTCS/MTHU006377]
  M N [] Seizures, generalized, afebrile [HPO2015_04_20/SY/HP:0002197]
  N Seizures, generalized, afebrile [OMIM2015_03_18/PTCS/MTHU002809]
  M N [] Infrequent generalized seizures [HPO2015_04_20/SY/HP:0002197]

**Comment by iamkoehler** [comment]
@pnrobinson Can you check what I have done now? Please reopen if I should improve the suggested solution. 
(There are two new classes (Afebrile seizures and Recurrent seizures) and the the conflicting synonyms are two classes now)

**Comment by mirandajarnot** [comment]
Hi –

Thanks for the quick reply.

Is there a way you could show us what you did on GitHub?
If not, could you link to your system so we can access it, preferably from GitHub where the initial issue was?
Not sure which would be easiest for you… please let me know.

Thanks,
Miranda

**Comment by iamkoehler** [comment]
At the moment the dev-version of HPO is on google-code svn, but this will be moved to github somewhen soon. The latest build of HPO is available at http://compbio.charite.de/hudson/job/hpo/

**Comment by mirandajarnot** [comment]
We need to be able to see the concepts in HPO so that we can make the appropriate changes in the Metathesaurus.  I am not at all familiar with you r site, and how to get to the information we need.
Could you perhaps cut and paste the concepts in question either into the GitHub comments (preferred) or into an email to me?

Thanks,
Miranda

**Comment by mellybelly** [comment]
@drseb especially until we move HPO to github and can reference commits here, can you paste in the HPO URIs and labels and what was changed? A link the file is great but would be helpful to have the content here for easy reference. thx.

**Comment by iamkoehler** [comment]
Ok, I will post a summary of the changes here, as soon as @pnrobinson has had a look at my suggested solution.

**Comment by mirandajarnot** [comment]
Great – Thank you!

Miranda

**Comment by pnrobinson** [comment]
=>HPO has "Afebrile Seizure" and "Recurrent Seizure" as synonyms. They are not the same thing and should not be SY. 
=> I agree with this and we should remove these from the main term.
=> Afebrile seizure is probably not a good HPO term. It is used in certain contexts to mean a seizure that a child had that was not a febrile seizure. However, most seizures (of all the many types listed now on the HPO) are afebrile.
=> Recurrent seizure is also not that great as a term. Most of the HPO terms are in the plural to indicate that we are talking not about a single seizure event (for instance, a seizure that happened to Mr Smith last Wednesday), but rather recurrent seizures of the type indicated. This terminology was discussed at length with epileptologists. In the future, if we ever want to model single seizure events, then we will need basically to duplicate the entire hierarchy but with terms in the singular form (eg we now have "absence seizures" to indicate the recurrent ones, but would need a new term "absence seizure" and so on for all of the various forms. In the differential diagnostic context that the HPO is now being used in, it is the recurrent seizures that are of interest.

**Comment by iamkoehler** [comment]
OK. Thanks Peter. No problem. I reverted the changes. 

In the end what we have changed now is to remove the two problematic synonyms from the class "Generalized seizures"
