### ISSUE TITLE
Time of death  [HP:0011420]

### ISSUE THREAD

**Issue by mirandajarnot** [monarch-initiative/HPO-UMLS-Integration#21]
The definition for this is:
(HPO2015_04_20) The age group when the cessation of life happens. [HPO:probinson]

Can you please clarify this definition?  Do you really mean age group, or do you mean time of day?

**Comment by iamkoehler** [comment]
This is referring to "age group", which relates to something like "neonatal" or "childhood"

**Comment by pnrobinson** [comment]
This should be renamed to "Age at death", thanks for picking up this error.  "Time of death" is simply incorrect.
