### ISSUE TITLE
HPO spelling of MedDRA

### ISSUE THREAD

**Issue by mirandajarnot** [monarch-initiative/HPO-UMLS-Integration#22]
We have noticed that HPO uses “MEDRA” instead of the correct spelling, “MEDDRA” in their xref values.  Is this intentional?  

Example:
[Term]
id: HP:0000023
name: Inguinal hernia
def: "Protrusion of the contents of the abdominal cavity through the inguinal canal." [HPO:probinson]
comment: Inguinal hernia appears as a bulge in the groin.
subset: hposlim_core
xref: MEDRA:10022016 "Inguinal hernia"
xref: MeSH:D006552 "Hernia, Inguinal"
xref: SNOMEDCT:396232000 "Inguinal hernia"
xref: UMLS:C0019294 "Hernias, Inguinal"
is_a: HP:0004299 ! Hernia of the abdominal wall

Thanks,
Miranda

**Comment by iamkoehler** [comment]
will fix this
