### ISSUE TITLE
Peripheral Arterial Disease  [HP:0004950]

### ISSUE THREAD

**Issue by mirandajarnot** [monarch-initiative/HPO-UMLS-Integration#23]
Peripheral Arterial Disease  [HP:0004950] has the synonym Peripheral Vascular Disease.  Should Peripheral Vascular Disease be in a separate, broader concept, since vascular diseases include both arterial and venous diseases?

**Comment by pnrobinson** [comment]
You are correct, and I see that we will need to rearrange several of the terms in this subhierarchy. Seb, could we do this next Wed or Thur?

**Comment by iamkoehler** [comment]
Wed would work for me. Added it to the calendar.

**Comment by pnrobinson** [comment]
Peripheral vascular disease is often used as a synonym for ARTERIAL (and not general vascular) disease. See the below text taken from [this website](http://www.emedicinehealth.com/peripheral_vascular_disease/article_em.htm).
We have therefore made the term a _related synonym_. I do not know of any useful classification of both venous AND arterial peripheral vascular diseases that would justify a new HPO subhierarchy, but if you have suggestions here we will of course reconsider!

> Peripheral vascular disease refers to any disease or disorder of the circulatory system outside of the brain and heart.
> - Although the term peripheral vascular disease can include any disorder that affects any of the blood vessels, it often is used as a synonym for peripheral artery disease.
> - Peripheral vascular disease is the most common disease of the arteries.
> -  It is caused by build-up of fatty material within the vessels, called atherosclerosis.
> - Another name for this condition is arteriosclerosis, or hardening of the arteries.
>   This is gradual process in which the artery gradually becomes blocked, narrowed, or weakened.
>   When this condition affects the arteries of the heart, it is called coronary heart disease (coronary artery disease).

**Comment by mirandajarnot** [comment]
Thanks for the reply.  I guess my dilemma  here is how to best represent HPO, while respecting the source information in the Metathesaurus. Since the two terms are used interchangeably some of the time, but not reliably, we cannot say for sure that they are completely synonymous, hence the two separate concepts in Meta.  I think that your making the two terms "related synonyms" in HPO should solve the problem for us.

Just as extra information, several sources clearly indicate that peripheral arterial disease is a TYPE of peripheral vascular disease, and therefore narrower in meaning:  

1)  American Heart Association:  "Peripheral artery disease (PAD) is a type of organic peripheral vascular disease (PVD). It’s caused by fatty buildups (atherosclerosis) in the inner walls of arteries."  [http://www.heart.org/idc/groups/heart-public/@wcm/@hcm/documents/downloadable/ucm_300323.pdf]

2)  Texas Heart Institute:  "Peripheral vascular disease (PVD) involves damage to or blockage in the blood vessels distant from your heart—the peripheral arteries and veins... When PVD affects only the arteries and not the veins, it is called peripheral arterial disease (PAD)."  [http://www.texasheart.org/HIC/Topics/Cond/pvd.cfm]

3)  Healthline:  "Peripheral vascular diseases (PVDs) are circulation disorders that affect blood vessels outside of the heart and brain. PVD typically strikes the veins and arteries that supply the arms, legs, and organs located below your stomach... PVD that develops only in the arteries is called peripheral arterial disease (PAD). This is the most common form of PVD."  [http://www.healthline.com/health/peripheral-vascular-disease#Overview1]

4)  The example you gave also states that PVA is a TYPE of PVD:  "Peripheral vascular disease refers to any disease or disorder of the circulatory system outside of the brain and heart.
Although the term peripheral vascular disease can include any disorder that affects ANY OF THE BLOOD VESSELS, it often is used as a synonym for peripheral artery disease."

Thanks again for the thoughtful consideration.

**Comment by pnrobinson** [comment]
I agree with the assessment given above. I think that a term such as "peripheral vascular disease" is a suboptimal term for the HPO anyway because it is not at all precise. Some of the terms in the subhierarchy eminating from the term "peripheral arterial disease" need revision. I am going to move this to the main HPO term request tracker for now. Please reopn this item if there are still issues.
thanks, Peter
PS sorry for the late reply to the last six items. The last two months have been brutally busy! Finally I have a few relatively quiet days!
