### ISSUE TITLE
Ankle Contracture  [HP:0006466]

### ISSUE THREAD

**Issue by mirandajarnot** [monarch-initiative/HPO-UMLS-Integration#24]
This concept has the synonym Knee and Ankle Contractures.  This is broader than Ankle Contractures; should it be a separate concept?  The definition here specifies the ankle joint, but says nothing about the knee joint.

**Comment by pnrobinson** [comment]
This is a mistake. Seb, could you remove this synonym?

**Comment by iamkoehler** [comment]
will do tomorrow
