### ISSUE TITLE
Alveolar Ridge Cleft vs. Gingival Cleft  [HP:0010289]

### ISSUE THREAD

**Issue by mirandajarnot** [monarch-initiative/HPO-UMLS-Integration#25]
HPO has these two terms as synonyms. We have separate concepts for them in the Metathesaurus.
It is clear what HPO means by Alveolar Ridge Cleft, but based on what I have found, it appears that Gingival Cleft has another meaning as well:  "Gingival cleft is defined as "an interdental fissure associated with pocket formation and lined by mixed gingival and pocket epithelium."  An alveolar ridge cleft means a cleft in the alveolar ridge, such as in cleft lip/palate.  
Can you please let me know how you define Gingival Cleft?
Thanks!

**Comment by markengelstad** [comment]
Hello Miranda,
I agree, they are definitely two distinct classes. 
Alveolar ridge includes gingiva, other mucosa, periosteum, alveolar bone, tooth structures. 
Gingiva includes only gingiva. 

the def for alveolar ridge cleft is "A gap (cleft) affecting one of the alveolar ridges".  I think this is appropriate, as you say. 

The current definition for gingival cleft does not make sense to me -- its too specific for a universal.  

I'd define it as: "An abnormal gap (cleft) within the gingiva"

**Comment by pnrobinson** [comment]
Sorry for the late response. I have added a new term "Gingival cleft", defined as A fissure in the gingiva (gums), i.e., the mucosal tissue that lies over the mandible and maxilla. (HP_0030690). I have transfered the database xrefs (UMLS, SNOMED) from Alveolar Ridge Cleft that actually refer to gingival cleft. I have extended the definition of Alveolar Ridge Cleft, to A gap (cleft) affecting one of the alveolar ridges, which are the protuberances in the mouth that contain the sockets (alveoli) of the teeth. An alveolar cleft can affect all structures of the alveolar ridge, including the gingiva, other mucosa, periosteum, alveolar bone, and teeth. and also added a ref to HPO:mengelstad (Thanks! Mark).

**Comment by cmungall** [comment]
Note that MP treats the ridge, bone and process as being synonymous, cc @cindyJax

```
[Term]
id: MP:0004189
name: abnormal alveolar process morphology
namespace: MPheno.ontology
def: "any structural anomaly of the thickened ridge of bone in the mandible and maxilla that holds the tooth sockets" [MGI:smb]
synonym: "abnormal alveolar body morphology" EXACT []
synonym: "abnormal alveolar bone morphology" EXACT []
synonym: "abnormal alveolar ridge morphology" EXACT []
is_a: MP:0000454  ! abnormal jaw morphology
```

We follow this in uberon and make equivalent a bunch of different concepts including the alveolar arch in FMA, and treat as a zone of bone

[UBERON:0004103](http://purl.obolibrary.org/obo/UBERON_0004103) ! alveolar ridge

Sounds like we should make the primary label for this concept be 'alveolar process' and reserve ridge to be the multi-tissue structure that includes both the process and associated tissue
