### ISSUE TITLE
HP:0001635  Congestive heart failure

### ISSUE THREAD

**Issue by mirandajarnot** [monarch-initiative/HPO-UMLS-Integration#26]
Congestive heart failure is the preferred term of this concept, but the synonyms Heart failure, Cardiac insufficiency, and Cardiac failure appear to be broader.  Also, the definition does not mention congestion or edema, so it is difficult to tell if the concept means specifically CHF or can mean any type of heart failure.  Can you please clarify your meaning for me?  Thank you!

**Comment by pnrobinson** [comment]
In practice, all these terms are used as synonyms. See the Wikipedia entry: https://en.wikipedia.org/wiki/Heart_failure. The term does have some subtypes that are in clinical use.

**Comment by mirandajarnot** [comment]
Thanks for your replies to these questions!
I appreciate your thoughtful explanations.

Thanks,
Miranda
