### ISSUE TITLE
wide cranial sutures

### ISSUE THREAD

**Issue by mirandajarnot** [monarch-initiative/HPO-UMLS-Integration#29]
HPO has the concept "Wide cranial sutures", HP:0010537.  
However, the same string, in singular form (wide cranial suture), appears in the concept "Large fontanelles", HP:0000239

Can you please clarify the use of this string in both places?  I understand the difference between the concepts, but the string similarity is problematic.

Thanks,
Miranda Jarnot

**Comment by markengelstad** [comment]
good catch.

that synonym is is misplaced and is removed from the pending lay term
update.

mee

**Comment by pnrobinson** [comment]
Thanks for picking this up, I have corrected the synonym
