### ISSUE TITLE
Scaphycephaly and Dolichocephaly

### ISSUE THREAD

**Issue by mirandajarnot** [monarch-initiative/HPO-UMLS-Integration#31]
HPO has the concept Dolichocephaly (HP:0000268), which has the synonym Scaphocephaly.  They are actually different; scaphocephaly is a form of dolichocephaly, and includes the formation of a distinct ridge on the top of the head.  Should they be in separate concepts?

**Comment by pnrobinson** [comment]
Thanks for this suggestion. I have added a new term scaphocephaly that is a child term of dolichocephaly.
