### ISSUE TITLE
Disorder of face (HP:0000271)

### ISSUE THREAD

**Issue by mirandajarnot** [monarch-initiative/HPO-UMLS-Integration#32]
This string is an entry term for the concept "Abnormality of the face".  They seem to mean slightly different things; a disorder and an abnormality are not necessarily synonymous.  Can you please explain the meaning here?  

Thanks,
Miranda Jarnot

**Comment by markengelstad** [comment]
'disorder of the face' is only a broad synonym currently

i agree we should avoid giving every 'Abnormality of  Z ' a synonym of
'Disorder of Z  ' ,

But disorder of face and anomaly of face are especially common clinical
terms, so having them somewhere in the HPO could be valuable.

In HPO they are not exact synonyms but are (should be) modeled as either
broad or narrow or maybe related synonym.

mee

**Comment by pnrobinson** [comment]
I agree with Mark that disorder of face is useful as a broad synonym of abnormality of face. Although the language is perhaps a little sloppy, I would not see any difference in the intended meaning.
