### ISSUE TITLE
HP:0006118  Shortening of all distal phalanges of fingers

### ISSUE THREAD

**Issue by mirandajarnot** [monarch-initiative/HPO-UMLS-Integration#33]
HPO has the term above as the preferred term of this concept.  It also has the synonym "Distal and middle phalangeal hypoplasia", which seems to be a different concept (broader) as it includes both distal and middle phalanges.  Can you please clarify your meaning here?  

Thanks,
Miranda Jarnot

**Comment by pnrobinson** [comment]
Thanks for picking up this mistake, I have corrected it.
