### ISSUE TITLE
HP:0007385  Aplasia cutis congenita of scalp

### ISSUE THREAD

**Issue by mirandajarnot** [monarch-initiative/HPO-UMLS-Integration#34]
This concept refers specifically to the disorder of the scalp.  However, there is a synonym in this concept, "aplasia cutis congenital (ACC)",  that is broader, and does not specify the site affected.  Should it be included here with the more specific scalp terms?

Thanks,
Miranda

**Comment by pnrobinson** [comment]
Thanks for picking this up, it was a mistake and I have now corrected it. Sorry for the late response to these issues, things have been massively busy for me this year!

**Comment by mirandajarnot** [comment]
No problem… same for us.  We are preparing for the April/May release of the UMLS.
Thanks for your attention to these queries!

Miranda
