### ISSUE TITLE
HP:0030412   Ilial adenocarcinoma

### ISSUE THREAD

**Issue by mirandajarnot** [monarch-initiative/HPO-UMLS-Integration#35]
Please consider changing the spelling here to "ileal" instead of "ilial", to distinguish ileum (intestine) from ilium (pelvis).

Thanks,
Miranda Jarnot

**Comment by pnrobinson** [comment]
Thanks for pointing this out, "ilial" is a mis-spelling in this context and we will correct it!

**Comment by mirandajarnot** [comment]
Thank you!
