### ISSUE TITLE
Parietal foramina  HP:0002697

### ISSUE THREAD

**Issue by mirandajarnot** [monarch-initiative/HPO-UMLS-Integration#36]
By "parietal foramina", do you mean foramina that are found normally in the human skull, or do you mean anatomically abnormal or disease-caused foramina?  It seems like the latter based on the HPO hierarchy, but the definition sounds more like the former.

Thanks,
Miranda Jarnot

**Comment by pnrobinson** [comment]
The HPO term is refering to holes that are not normally present in the parietal bones. As far as I know the normal adult parietal does not have foramina, see https://en.wikipedia.org/wiki/Parietal_bone. The comment of the HPO term also states that the foramina are abnormal.
