### ISSUE TITLE
Abnormality of cranial sutures

### ISSUE THREAD

**Issue by mirandajarnot** [monarch-initiative/HPO-UMLS-Integration#37]
HPO has two concepts that appear to mean the same thing, at least in part.
HP:0000235 "Abnormality of the fontanelles or cranial sutures" -- This concept has the synonym "abnormality of the cranial sutures".  However, the concept HP:0011329  "Abnormality of cranial sutures" also exists.  If they are truly separate, could you please clarify for me the synonyms and definitions?  I want to make sure we have it right in the UMLS.

Thanks,
Miranda Jarnot

**Comment by iamkoehler** [comment]
I moved several synonyms from "Abnormality of the fontanelles or cranial sutures" to "Abnormality of cranial sutures"

"Abnormality of the fontanelles or cranial sutures" is referring to the union of all abnormalities of the sutures or fontanelles.

**Comment by mirandajarnot** [comment]
Thank you!  I thought that was what you meant, but the synonyms were confusing.
I’ll make sure they are represented correctly in the UMLS.

Miranda
