### ISSUE TITLE
UMLS:C1859424

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/HPO-UMLS-Integration#38]
Please note that I have revised the structure around the "Abnormality of chromosome stability" and I have transfered the UMLS term UMLS:C18 from "Abnormality of chromosome stability" to the HPO term "Chromosome breakage" (which is a child of "Abnormality of chromosome stability").

**Comment by iamkoehler** [comment]
@mirandajarnot have you noticed this? Can we close this issue?

**Comment by mirandajarnot** [comment]
Yes, please.

**Comment by iamkoehler** [comment]
Thanks!
