### ISSUE TITLE
Meta Concepts #26006 Pain in scrotum and #15203  Gait, Unsteady

### ISSUE THREAD

**Issue by mirandajarnot** [monarch-initiative/HPO-UMLS-Integration#4]
The HPO contexts for both of these is Phenotypic Abnormality.  The STYs are Sign or Symptom for "pain in scrotum" and Finding for "gait, unsteady".  There are other examples like this; do they truly mean Abnormality, or is Sign or Symptom/Finding OK?

CN# 26006  Pain in scrotum
CUI C0236078    Concept Status needs Review
STY Sign or Symptom   R
DEF [Release] HPO2015_04_20
- HPO2015_04_20/PT|An unpleasant sensation characterized by
  physical discomfort (such as pricking, throbbing, or aching)
  localized to the scrotum. []
  DEF [Release] NCI2015_02D
- NCI2015_02D/PT|Painful sensation in the scrotal area.
  DEF [Release] NCI2015_CTCAE_1502D
- NCI2015_02D/PT|A disorder characterized by marked discomfort
  sensation in the scrotal area.
  ATOMS
             R []  Pain in scrotum [MTH/PN/NOCODE]
             R        Pain in scrotum [SNOMEDCT_US_2015_03_01/PT/20502007]
             R      Pain of scrotum [SNOMEDCT_US_2015_03_01/SY/20502007]
             R      pain; scrotum [ICPC2ICD10ENG_200412/PT/MTHU059607]
             R      scrotum; pain [ICPC2ICD10ENG_200412/PT/MTHU066991]
  Y           R      SCROTUM PAIN <2> [MTH/TM/U160988]
               R []  Pain in scrotum (finding) [SNOMEDCT_US_2015_03_01/FN/20502007]
               R []  Scrotal pain [SNOMEDCT_US_2015_03_01/SY/20502007]
  M            N        Scrotal pain [HPO2015_04_20/PT/HP:0030155]
             R        Scrotal pain [NCI2015_CTCAE_1502D/PT/E13201] C78607
             R      Scrotal Pain [NCI2015_02D/PT/C78607] C78607
             R []  Scrotum painful [SNOMEDCT_VET_2015_04_01/SY/20502007]

CONTEXTS
   HPO2015_04_20/HPO2015_04_20/PT1/HP:0030155
   HPO
     All
       Phenotypic abnormality
         Abnormality of the genitourinary system
           Abnormality of the genital system
             Abnormal genital system morphology
               Abnormal external genitalia
                 Abnormality of male external genitalia
                   Abnormality of the scrotum
                     Abnormal scrotal rugation +
                     Absent scrotum
                     Accessory scrotum
                     Bifid scrotum
                     Ectopic scrotum
                     Neoplasm of the scrotum
                     Penoscrotal transposition
                     Prominent scrotal raphe
                     Scrotal hyperpgimentation
                     Scrotal hypoplasia
                    <Scrotal pain>
                     Shawl scrotum
                     Small scrotum
                     Vaginal hematocele
                     Vaginal hydrocele
                     Vaginal lymphocele
                     Vaginal pyocele
                     Varicocele
   HPO2015_04_20/HPO2015_04_20/PT2/HP:0030155
   HPO
     All
       Phenotypic abnormality
         Abnormality of the genitourinary system
           Abnormality of the genital system
             Abnormal genital system morphology
               Abnormality of the male genitalia
                 Abnormality of male external genitalia
                   Abnormality of the scrotum
                     Abnormal scrotal rugation +
                     Absent scrotum
                     Accessory scrotum
                     Bifid scrotum
                     Ectopic scrotum
                     Neoplasm of the scrotum
                     Penoscrotal transposition
                     Prominent scrotal raphe
                     Scrotal hyperpgimentation
                     Scrotal hypoplasia
                    <Scrotal pain>
                     Shawl scrotum
                     Small scrotum
                     Vaginal hematocele
                     Vaginal hydrocele
                     Vaginal lymphocele
                     Vaginal pyocele
                     Varicocele
   NCI2015_02D/NCI2015_02D/PT1/C78607
   National Cancer Institute Thesaurus
     Disease, Disorder or Finding
       Finding
         Sign or Symptom
           Symptom
             Pain
               Skin Pain
                <Scrotal Pain
SNOMEDCT_US_2015_03_01/SNOMEDCT_US_2015_03_01/PT1/20502007
   SNOMED CT Concept
     Clinical finding
       Finding by site
         Finding of body region
           Finding of trunk structure
             Finding of pelvic region of trunk
               Male genitalia finding
                 Pain in male genitalia
                  <Pain in scrotum>
   SNOMEDCT_US_2015_03_01/SNOMEDCT_US_2015_03_01/PT2/20502007
   SNOMED CT Concept
     Clinical finding
       Finding by site
         Finding of body region
           Finding of trunk structure
             Urogenital finding
               Genital finding
                 Male genitalia finding
                   Pain in male genitalia
                    <Pain in scrotum>
   SNOMEDCT_US_2015_03_01/SNOMEDCT_US_2015_03_01/PT3/20502007
   SNOMED CT Concept
     Clinical finding
       Finding by site
         Finding of body region
           Finding of trunk structure
             Urogenital finding
               Genitourinary pain
                 Pain in male genitalia
                  <Pain in scrotum>
   SNOMEDCT_US_2015_03_01/SNOMEDCT_US_2015_03_01/PT4/20502007
   SNOMED CT Concept
     Clinical finding
       Finding by site
         Finding of sensation by site
           Pain finding at anatomical site
             Pain of truncal structure
               Pain in pelvis
                 Genitourinary pain
                   Pain in male genitalia
                    <Pain in scrotum>
   SNOMEDCT_US_2015_03_01/SNOMEDCT_US_2015_03_01/PT5/20502007
   SNOMED CT Concept
     Clinical finding
       Neurological finding
         Sensory nervous system finding
           Finding of sensation by site
             Pain finding at anatomical site
               Pain of truncal structure
                 Pain in pelvis
                   Genitourinary pain
                     Pain in male genitalia
                      <Pain in scrotum>
   SNOMEDCT_US_2015_03_01/SNOMEDCT_US_2015_03_01/PT6/20502007
   SNOMED CT Concept
     Clinical finding
       Neurological finding
         Sensory nervous system finding
           Pain / sensation finding
             Pain
               Pain finding at anatomical site
                 Pain of truncal structure
                   Pain in pelvis
                     Genitourinary pain
                       Pain in male genitalia
                        <Pain in scrotum>
   SNOMEDCT_US_2015_03_01/SNOMEDCT_US_2015_03_01/PT7/20502007
   SNOMED CT Concept
     Clinical finding
       Finding by site
         Finding of body region
           Finding of trunk structure
             Pain of truncal structure
               Pain in pelvis
                 Genitourinary pain
                   Pain in male genitalia
                    <Pain in scrotum>
   SNOMEDCT_US_2015_03_01/SNOMEDCT_US_2015_03_01/PT8/20502007
   SNOMED CT Concept
     Clinical finding
       Finding by site
         Finding of body region
           Finding of trunk structure
             Finding of pelvic region of trunk
               Pain in pelvis
                 Genitourinary pain
                   Pain in male genitalia
                    <Pain in scrotum>

CN# 15203  Gait, Unsteady
CUI C0231686    Concept Status needs Review
STY Finding   R
ATOMS
               R []  Gait, Unsteady [MSH2015_2015_01_26/PEN/D020233] M0337784
               R      Unsteady gait [SNOMEDCT_US_2015_03_01/PT/394616008]
M            N        Unsteady gait [HPO2015_04_20/PT/HP:0002317]
               R        Unsteady gait [OMIM2015_03_18/PTCS/MTHU002478]
               R        Unsteady gait [LNC250/CN/MTHU020852]
               R      Unsteady Gait [MSH2015_2015_01_26/PM/D020233] M0337784
               R []  Unsteady gait (finding) [SNOMEDCT_US_2015_03_01/FN/394616008]
               R []  Unsteady when walking (finding) [SNOMEDCT_US_2015_03_01/FN/22631008]
               R []  Unsteady when walking [SNOMEDCT_US_2015_03_01/PT/22631008]
               R []  Disequilibrium when walking [SNOMEDCT_US_2015_03_01/SY/22631008]
               R []  Instability of gait [SNOMEDCT_US_2015_03_01/SY/394616008]
M            N      Gait instability [HPO2015_04_20/SY/HP:0002317]
               R      Instability gait [MDR18_0/LT/10022455]
               R []  Unstable when walking [SNOMEDCT_US_2015_03_01/SY/22631008]
               R []  Unstable gait [OMIM2015_03_18/PTCS/MTHU011036]

CONTEXTS
HPO2015_04_20/HPO2015_04_20/PT1/HP:0002317
   HPO
     All
       Phenotypic abnormality
         Abnormality of the nervous system
           Abnormality of nervous system physiology
             Abnormality of movement
               Gait disturbance
                 Broad-based gait
                 Cerebellar ataxia associated with quadrupedal gait
                 Difficulty walking
                 Falls
                 Gait apraxia
                 Gait ataxia +
                 Gait imbalance
                 Inability to walk +
                 Scissor gait
                 Shuffling gait +
                 Steppage gait
                 Tip-toe gait
                 Toe walking
                <Unsteady gait>
                 Waddling gait
   SNOMEDCT_US_2015_03_01/SNOMEDCT_US_2015_03_01/PT1/22631008
   SNOMED CT Concept
     Clinical finding
       Clinical history and observation findings
         Functional finding
           Finding of walking
             Finding of gait
               Abnormal gait
                <Unsteady when walking>
   SNOMEDCT_US_2015_03_01/SNOMEDCT_US_2015_03_01/PT1/394616008
   SNOMED CT Concept
     Clinical finding
       Clinical history and observation findings
         Functional finding
           Finding of walking
             Finding of gait
              <Unsteady gait>
   SNOMEDCT_US_2015_03_01/SNOMEDCT_US_2015_03_01/PT2/22631008
   SNOMED CT Concept
     Clinical finding
       Clinical history and observation findings
         Finding of balance
           Finding of walking balance
            <Unsteady when walking>

**Comment by pnrobinson** [comment]
The HPO has treated symptoms as a subclass of phenotypic abnormality. This is because there is a clinical abnormality of one sort or another that leads to say pain but if we looked at it under the microscope we would see some sign of inflammation or tissue damage etc.  Signs are by definition phenotypic abnormalities because they are things that a doctor observes as abnormal.
Do you not agree that a sign/symptom is an abnormality?

**Comment by mirandajarnot** [comment]
I see your point about symptoms as a subclass of abnormality.
Based on your response we have decided that we will leave the HPO atom where it merged 
into the same concept as strings from other sources including
Pain in scrotum [SNOMEDCT /PT/20502007] 

And Unsteady Gait will stay in the same concept as:
Gait, Unsteady [MSH2015_2015_01_26/PEN/D020233]
Unsteady gait [SNOMEDCT_US_2015_03_01/PT/394616008]
Along with several other sources.

Thanks, Miranda
