### ISSUE TITLE
Data issue:  "obsolete"

### ISSUE THREAD

**Issue by mirandajarnot** [monarch-initiative/HPO-UMLS-Integration#48]
There is a tiny data issue. It was present in the last version also, but we did not notice it then. 

For all other records where "is_obsolete" = true, the name is preceded by "obsolete" (e.g. "name: obsolete Abnormal heart morphology") 

This record is the exception. 

This is in the obo file:
[Term]
id: HP:0100805
name: Precocious menopause
is_obsolete: true

**Comment by pnrobinson** [comment]
Thanks, I just corrected this.
