### ISSUE TITLE
Finger Joint Hyperextensibility

### ISSUE THREAD

**Issue by mirandajarnot** [monarch-initiative/HPO-UMLS-Integration#5]
We have merged these two HPO PTs together into the same concept in UMLS (#44592108):

Finger joint hyperextensibility [HPO2015_04_20/PT/HP:0006158]
Hyperextensibility of the finger joints [HPO2015_04_20/PT/HP:0001187]

If they are not synonymous in HPO, please let us know why they are not.

Thanks,
Miranda Jarnot

**Comment by iamkoehler** [comment]
Thanks for reporting this.

I have merged these in HPO and did some correction to the subclass hierarchy.
