### ISSUE TITLE
HPO typos from 2020_10_12_hp.obo.txt file, from UMLS

### ISSUE THREAD

**Issue by mirandajarnot** [monarch-initiative/HPO-UMLS-Integration#54]
Please let me know if you need more information -- thanks, Miranda Jarnot

Names/synonyms:
Abnromal
Dminished
abcess
cirulating
concenrtation
concentraions

Definitions:  
Abormality
ntrationl
inflammed
Persistance
ahcievement
airsspaces
apperance
awarness
betweem
bloood
comon
concentrationl
deivation
diseaes
elswehere
extreemely
immunocompentent
impairement
intial
lenghten
leuucine
lfibrosis
ltubular
mulitple
ncomment
ngative
nnComment
nseeAlso
nsource
numbersof
obstuction
occcasionally
occured
occurunder
pdenuculated
peniile
processinvolving
ranghes
rarified
reponse
rhytm
seconday
severety
suger
sytems
thehead
thickend
thicknes
tisssue
tricpes
wich
with

**Comment by pnrobinson** [comment]
I will cross ref this issue from the HPO tracker and fix the issues that remain before the next release.

**Comment by pnrobinson** [comment]
fixed, thanks
