### ISSUE TITLE
UMLS -- obsolete record is missing a "name" tag

### ISSUE THREAD

**Issue by mirandajarnot** [monarch-initiative/HPO-UMLS-Integration#55]
One obsolete record is missing a "name" tag (what we invert as the string, so it’s a showstopper).  This is the obo because it's more readable, but it's the same in the owl.

We don’t need a new file.  For the future, I updated the script to report these cases but drop them from the inversion.  

[Term]
id: HP:4000080
is_obsolete: true
replaced_by: HP:5200027

**Comment by pnrobinson** [comment]
The original label of the term got lost. I added the label Obsoleted 4000080 for consistency, but obviously the term should not be used anymore.
