### ISSUE TITLE
Spelling error, id: HP:5200201

### ISSUE THREAD

**Issue by mirandajarnot** [monarch-initiative/HPO-UMLS-Integration#56]
Please see spelling error below... **Hallucinatotions**

id: HP:5200201
name: Gustatory hallucination
def: "Perception of taste without gustatory stimulus." []
synonym: "**Hallucinatotions** of taste" EXACT []
synonym: "Taste hallucination" EXACT []

Thanks,
Miranda Jarnot, UMLS

**Comment by pnrobinson** [comment]
fixed
