### ISSUE TITLE
Spelling error, id: HP:0041092

### ISSUE THREAD

**Issue by mirandajarnot** [monarch-initiative/HPO-UMLS-Integration#57]
Please see spelling error below... **reacitivy**

id: HP:0041092
name: Emotional hypersensitivity
def: "Heightened emotional reactivity to environmental stimuli, including the emotions of others." []
synonym: "Emotional **reacitivy**" EXACT []

Thanks,
Miranda Jarnot, UMLS

**Comment by pnrobinson** [comment]
fixed
