### ISSUE TITLE
Orbital cyst(s)

### ISSUE THREAD

**Issue by mirandajarnot** [monarch-initiative/HPO-UMLS-Integration#8]
The HPO concept HP:0001144 has the terms Orbital cyst (PT) and Orbital cysts (ET).  Because Meta considers singular and plural terms synonymous, we have merged both into the Meta concept Orbital cyst (disorder).  Does HPO also consider these synonymous?  The use of the term type ET rather than SY is the reason I ask.  
Thank you!

**Comment by iamkoehler** [comment]
Can you explain what PT, ET, and SY mean?

**Comment by mirandajarnot** [comment]
PT = designated preferred name
ET = entry term
SY = designated synonym

**Comment by iamkoehler** [comment]
I have now made "Orbital cysts" an 'exact' synonym, which was defined as 'related' synonym before. Does this solve this problem?

**Comment by mirandajarnot** [comment]
Yes... that is perfect.  Thanks!
There are others like this.  Do you want me to submit them one at a time, or compile a list?

**Comment by iamkoehler** [comment]
Yes, I have made that 'error' multiple times. I am fine with both, a compiled list or one-by-one. Whatever you prefer.
