### ISSUE TITLE
Adrenal hypoplasia

### ISSUE THREAD

**Issue by mirandajarnot** [monarch-initiative/HPO-UMLS-Integration#9]
HPO has the concepts Congenital adrenal hypoplasia (HP:0008244) and Adrenal hypoplasia (HP:0000835).  Based on the definition of "hypoplasia" as a congenital condition, should these be considered synonymous?

**Comment by markengelstad** [comment]
i've looked at many congenital **\*  concepts in head and neck terms and
have noted that _'present at birth'_ is included in all of their textual
definition but not their logical definitions.

Logically, 'Congenital Onset' is subset of 'Clinical modifier' and
logically modeled as
Onset
and ('existence starts during' some ' prenatal stage')

But we don't seem to be using that in our logical definitions of (most?)
congenital **\* concepts.

Mark

**Comment by pnrobinson** [comment]
I do not agree that hypoplasia is always congenital, it basically means under-growth or under-development and growth is obviously not finished when one is born. In some differential diagnoses, the notion of "congenital" really narrows things down, and in these cases we have tended to leave the term. In general, it is also possible to modify any term in the HPO with the modifier "Congenital onset".

**Comment by mirandajarnot** [comment]
Thanks for the clarification.  We have left these separate in the Metathesaurus.
